<ScreenOne>:
    BoxLayout:
        orientation: 'vertical'
        Label:
            text: "This is Screen One"
        Button:
            text: "Go to Screen Two"
            on_release: app.root.current = "screen2"

<ScreenTwo>:
    BoxLayout:
        orientation: 'vertical'
        Label:
            text: "This is Screen Two"
        Button:
            text: "Go to Screen One"
            on_release: app.root.current = "screen1"
